webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/ViewModels/Jelo/JeloDodajVM.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Jelo
{
    public class JeloDodajVM
    {

        public int JeloId { get; set; }
        public int SastojciId { get; set; }
        public List<SelectListItem> sastojciLista { get; set; }

        public List<int> sastojciOdabrani { get; set; }

        [BindRequired]
        public int VrstaJelaId { get; set; }
    
        public List<SelectListItem> vrstaJelaLista { get; set; }

        [Required(ErrorMessage="Naziv jela je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Opis mora imat više od 4 slova")]
        public string Naziv { get; set; }

        [Required(ErrorMessage = "Opis je obavezno polje")]
        [RegularExpression("^.{6,}$", ErrorMessage = "Opis mora imat više od 6 slova")]
        public string Opis { get; set; }

        [Required(ErrorMessage = "Cijena je obavezno polje")]
        [RegularExpression("^(?(?=99)99(\\.0+)?|([1-9]\\d?(\\.\\d+)?))$", ErrorMessage = "Cijena mora biti veća od 0 i manja od 100")]
        public float Cijena { get; set; }

        public IFormFile Slika { get; set; }
       
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/ViewModels/Jelo/JeloListVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Jelo
{
    public class JeloListVM
    {
        public class SastojakVM
        {
            public string Naziv { get; set; }
            public string Opis { get; set; }

        }
        public class Row
        {
            public int Id { get; set; }
            public string Naziv { get; set; }
            public float Cijena { get; set; }
            public string Opis { get; set; }

            public string VrstaJela { get; set; }

            public List<SastojakVM> Sastojci { get; set; }
            public string Slika { get; set; }
        }
        public List<Row> htmlRows { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/ViewModels/Jelo/JeloVrstaDodaj.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Jelo
{
    public class JeloVrstaDodaj
    {
        public int VrstaJelaId { get; set; }

        [Required(ErrorMessage = "Naziv je obavezno polje")]
        [RegularExpression("^.{2,}$", ErrorMessage = "Naziv mora imat više od 2 karaktera")]
        public string Naziv { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/ViewModels/Jelo/JeloIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebApplication1.Areas.ModulKorisnik.ViewModels.Jelo
{
    public class JeloIndexVM
    {
        public class SastojakVM
        {
            public string Naziv { get; set; }
            public string Opis { get; set; }

        }
        public class Row
        {
            public int Id { get; set; }
            public string Naziv { get; set; }
            public float Cijena { get; set; }
            public string Opis { get; set; }

            public string VrstaJela { get; set; }

            public List<SastojakVM> Sastojci { get; set; }
            public string Slika { get; set; }
        }
        public List<Row> Rows { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Models/Jelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Jelo
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Molimo unesite naziv")]
        public string Naziv { get; set; }

        [Required(ErrorMessage = "Molimo unesite cijenu")]
        public float Cijena { get; set;  }
        public string Opis { get; set; }
        public string JedinicaMjere { get; set; }
        public string Slika { get; set; }

        public int VrstaJelaID { get; set; }
        [ForeignKey("VrstaJelaID")]
        public VrstaJela VrstaJela { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/Controllers/JeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Areas.ModulAdmin.ViewModels.Jelo;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Helper;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace WebApplication1.Areas.ModulAdmin.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: false)]

    [Area("ModulAdmin")]
    [Route("/ModulAdmin/Jelo")]
    public class JeloController : Controller
    {
        private MyContext db;
        private readonly IHostingEnvironment hostingEnvironment;
        public JeloController(MyContext baza, 
                              IHostingEnvironment hostingEnvironment)
        {
            
            db = baza;
            this.hostingEnvironment = hostingEnvironment;
        }


        [Route("/ModulAdmin/Jelo/List")]
        public IActionResult List()
        {

            JeloListVM model = new JeloListVM
            {
                htmlRows = db.Jelo.Select(j => new JeloListVM.Row()
                {
                    Id = j.Id,
                    Naziv = j.Naziv,
                    VrstaJela = j.VrstaJela.Naziv,
                    Opis = j.Opis,
                    Cijena = j.Cijena,
                    Slika = j.Slika,
                    Sastojci = db.ImaSastojke.Where(s => s.JeloId == j.Id).Select(q => new JeloListVM.SastojakVM
                    {
                        Naziv = q.Sastojci.Naziv,
                        Opis = q.Sastojci.Opis
                    }).ToList()

                }).ToList()
            };


            return View(model);
        }
        [Route("/ModulAdmin/Jelo/Obrisi")]
        [HttpGet]
        public IActionResult Obrisi(int id)
        {
            Jelo obrisati = db.Jelo.SingleOrDefault(j => j.Id == id);

            if (obrisati == null)
                return View("Error");

            db.Remove(obrisati);
            db.SaveChanges();
            TempData["porukaDelete"] = "Uspjesno obrisan korisnik";

            return RedirectToAction("List");
        }

        [Route("/ModulAdmin/Jelo/Dodaj")]
        public IActionResult Dodaj()
        {
            var model = new JeloDodajVM();
            GenerisiCmbStavke(model);


            return View(model);
        }

        [Route("/ModulAdmin/Jelo/DodajVrstuJela")]

        public IActionResult DodajVrstuJela()
        {
            var model = new JeloVrstaDodaj();

            return View(model);
        }
        [Route("/ModulAdmin/Jelo/DodajVrstuSave")]

        public IActionResult DodajVrstuSave(JeloVrstaDodaj model)
        {
            if (ModelState.IsValid)
            {
                VrstaJela vrsta = db.VrstaJela.Find(model.VrstaJelaId);

                if (vrsta == null)
                {
                    vrsta = new VrstaJela();
                    db.Add(vrsta);
                }

                vrsta.Naziv = model.Naziv;
                
                db.SaveChanges();

                return RedirectToAction("Dodaj");

            }
            else
            {
                return View("DodajVrstuJela", model);
            }
        }

        [Route("/ModulAdmin/Jelo/Uredi")]
        [HttpGet]

        public IActionResult Uredi(int id)
        {
            Jelo jelo = db.Jelo.Find(id);
            

            JeloDodajVM model = new JeloDodajVM();
            GenerisiCmbStavke(model);

            model.JeloId = id;
            model.Cijena = jelo.Cijena;
            model.Naziv = jelo.Naziv;
            model.Opis = jelo.Opis;
            model.VrstaJelaId = jelo.VrstaJelaID;


            IQueryable<ImaSastojke> imaSastojkes = db.ImaSastojke.Where(w => w.JeloId == id);

            foreach(ImaSastojke iS in imaSastojkes)
            {
                db.Remove(iS);
               
            }
            db.SaveChanges();
            return View(model);
        }

         private void GenerisiCmbStavke(JeloDodajVM model)
        {

            model.sastojciLista = db.Sastojci.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.Id.ToString()
            }).ToList();
            model.vrstaJelaLista = db.VrstaJela.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.Id.ToString()
            }).ToList();

        }

        
        [Route("/ModulAdmin/Jelo/DodajSave")]
        [HttpPost]
        public IActionResult DodajSave(JeloDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Jelo jelo = db.Jelo.Find(model.JeloId);

                if (jelo == null)
                {
                    jelo = new Jelo();
                    db.Add(jelo);
                }
                string uniqueFileName = null;
                if(model.Slika != null)
                {
                   string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                   uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Slika.FileName;
                   string filePath =  Path.Combine(uploadsFolder, uniqueFileName);
                    model.Slika.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                jelo.Cijena = model.Cijena;
                jelo.Naziv = model.Naziv;
                jelo.Opis = model.Opis;
                jelo.VrstaJelaID = model.VrstaJelaId;
                jelo.Slika = uniqueFileName;


               

                Jelo x = db.Jelo.Where(y => y.Id == jelo.Id).SingleOrDefault();


                foreach (int s in model.sastojciOdabrani)
                {
                    ImaSastojke iS = new ImaSastojke
                    {
                        JeloId = x.Id,
                        SastojciId = s
                    };
                    db.Add(iS);
                }
                db.SaveChanges();
                return RedirectToAction("List");
           

            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Dodaj",model);
            }
        }
        [Route("/ModulAdmin/Jelo/UrediSave")]
        [HttpPost]
        public IActionResult UrediSave(JeloDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Jelo jelo = db.Jelo.Find(model.JeloId);

                if (jelo == null)
                {
                    jelo = new Jelo();
                    db.Add(jelo);
                }
                string uniqueFileName = null;
                if (model.Slika != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Slika.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Slika.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                jelo.Cijena = model.Cijena;
                jelo.Naziv = model.Naziv;
                jelo.Opis = model.Opis;
                jelo.VrstaJelaID = model.VrstaJelaId;
                jelo.Slika = uniqueFileName;


                Jelo x = db.Jelo.Where(y => y.Id == jelo.Id).SingleOrDefault();


                foreach (int s in model.sastojciOdabrani)
                {
                    ImaSastojke iS = new ImaSastojke
                    {
                        JeloId = x.Id,
                        SastojciId = s
                    };
                    db.Add(iS);
                }
                db.SaveChanges();

                return RedirectToAction("List");

            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Uredi", model);
            }
        }

    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/Controllers/JeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.EF;
using WebApplication1.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Helper;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using WebApplication1.Areas.ModulKorisnik.ViewModels.Jelo;

namespace WebApplication1.Areas.ModulKorisnik.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: true)]

    [Area("ModulKorisnik")]
    [Route("/ModulKorisnik/Jelo")]
    public class JeloController : Controller
    {
        private MyContext db;
        private readonly IHostingEnvironment hostingEnvironment;
        public JeloController(MyContext baza,
                              IHostingEnvironment hostingEnvironment)
        {

            db = baza;
            this.hostingEnvironment = hostingEnvironment;
        }


        [Route("/ModulKorisnik/Jelo/Index")]
        public IActionResult Index()
        {

            JeloIndexVM model = new JeloIndexVM
            {
                Rows = db.Jelo.Select(j => new JeloIndexVM.Row()
                {
                    Id = j.Id,
                    Naziv = j.Naziv,
                    VrstaJela = j.VrstaJela.Naziv,
                    Opis = j.Opis,
                    Cijena = j.Cijena,
                    Slika = j.Slika,
                    Sastojci = db.ImaSastojke.Where(s => s.JeloId == j.Id).Select(q => new JeloIndexVM.SastojakVM
                    {
                        Naziv = q.Sastojci.Naziv,
                        Opis = q.Sastojci.Opis
                    }).ToList()

                }).ToList()
            };


            return View(model);
        }
        

        
        

    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/Views/Jelo/Dodaj.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Jelo.JeloDodajVM

@{
    ViewData["Title"] = "Dodaj jelo";


}


<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj jelo</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form enctype="multipart/form-data"  asp-controller="Jelo" asp-action="DodajSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">

                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Naziv" type="text" class="form-control" name="Naziv">
                            <span asp-validation-for="Naziv"></span>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="vrsta">
                            Vrsta jela:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div class="input-group">

                                <select asp-for="VrstaJelaId" asp-items="Model.vrstaJelaLista" class="form-control">
                                    <option value="" disabled hidden selected>(Odaberi vrstu jela)</option>
                                </select>
                                <span class="input-group-btn">
                                    <a asp-controller="Jelo" asp-action="DodajVrstuJela" class="btn btn-primary">Dodaj</a>
                                </span>
                            </div>
                            <span asp-validation-for="VrstaJelaId"></span>

                        </div>
                    </div>


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Cijena">
                            Cijena
                        </label>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            <input asp-for="Cijena" required="required" class="form-control" />
                            <span asp-validation-for="Cijena"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Opis: </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea asp-for="Opis" rows="3" style="resize:none" class="form-control"></textarea>
                            <span asp-validation-for="Opis"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            Sastojci:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select asp-for="sastojciOdabrani" asp-items="Model.sastojciLista" required class="select2_multiple form-control" multiple="multiple"></select>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Slika">
                            Slika
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Slika" required="required" class="form-control custom-file-input" />
                            <label class="custom-file-label">Izaberite sliku...</label>
                        </div>
                    </div>
                    <input asp-for="JeloId" type="hidden" />

                    <div class="form-group">
                        <div class="col-md-9 text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Potvrdi</button>

                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>





@*<script>
    function ValidirajGrad() {

        var element = document.getElementById("VrstaJelaId");
        var error = document.getElementById("VrstaJelaError");

        if (element[0].selected == true) {
            element.classList.add("input-validation-error");
            error.classList.remove("field-validation-valid");
            error.classList.add("field-validation-error");
            error.innerHTML = "*Odaberite vrstu jela iz opadajuće liste ili dodajte novi klikom na '...'";

            return false;
        }
        else {
            element.classList.remove("input-validation-error");
            error.classList.remove("field-validation-error");
            error.classList.add("field-validation-valid");
            error.innerHTML = "";
            return true;
        }

    }
</script>*@


@*<div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Dodaj jelo</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form asp-action="DodajSave" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                First Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Naziv: </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input asp-for="Naziv" id="first-name" required="required" class="form-control col-md-7 col-xs-12" />
                                <span class="field-validation-valid" data-valmsg-for="Naziv" data-valmsg-replace="true"></span>
                                <span class="field-validation-valid" data-valmsg-for="NazivError" data-valmsg-replace="true" id="NazivError"></span>
                            </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                    Last Name <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Middle Name / Initial</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input id="middle-name" class="form-control col-md-7 col-xs-12" type="text" name="middle-name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Gender</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div id="gender" class="btn-group" data-toggle="buttons">
                                        <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="gender" value="male"> &nbsp; Male &nbsp;
                                        </label>
                                        <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="gender" value="female"> Female
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                    Date Of Birth <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required" type="text">
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-primary" type="button">Cancel</button>
                                    <button class="btn btn-primary" type="reset">Reset</button>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>

    </form>
                </div>
            </div>
        </div>
    </div>*@

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/Views/Jelo/DodajVrstuJela.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Jelo.JeloVrstaDodaj

@{
    ViewData["Title"] = "Dodaj vrstu jela";


}


<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Dodaj vrstu jela</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form asp-controller="Jelo" asp-action="DodajVrstuSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">

                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Naziv" type="text" class="form-control" name="Naziv">
                            <span asp-validation-for="Naziv"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-9 text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Potvrdi</button>

                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/Views/Jelo/Uredi.cshtml
@model WebApplication1.Areas.ModulAdmin.ViewModels.Jelo.JeloDodajVM
<!-- Modal -->

<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Dodaj jelo</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form asp-controller="Jelo" enctype="multipart/form-data" asp-action="UrediSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Naziv">

                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input asp-for="Naziv" autofocus type="text" class="form-control" name="Naziv">
                        <span asp-validation-for="Naziv"></span>

                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="vrsta">
                        Vrsta jela:
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select asp-for="VrstaJelaId" asp-items="Model.vrstaJelaLista" class="form-control">
                            <option value="" disabled hidden selected>(Odaberi vrstu jela)</option>
                        </select>
                        <span asp-validation-for="VrstaJelaId"></span>

                    </div>
                </div>


                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Cijena">
                        Cijena
                    </label>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        <input asp-for="Cijena" required="required" class="form-control" />
                        <span asp-validation-for="Cijena"></span>
                    </div>

                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Opis: </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea asp-for="Opis" rows="3" style="resize:none" class="form-control"></textarea>
                        <span asp-validation-for="Opis"></span>

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        Sastojci:
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select asp-for="sastojciOdabrani" asp-items="Model.sastojciLista" required class="select2_multiple form-control" multiple="multiple"></select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Slika">
                        Slika
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input asp-for="Slika" required="required" class="form-control custom-file-input" />
                        <label class="custom-file-label">Izaberite sliku...</label>
                    </div>
                </div>
                <input asp-for="JeloId" type="hidden" />

                <div class="form-group">
                    <div class="col-md-9 text-right">
                        <button type="reset" class="btn btn-primary">Resetiraj</button>
                        <button type="submit" class="btn btn-success">Potvrdi</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
</div>