webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/ViewModels/Kontakt/KontaktIndexVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Areas.ModulKorisnik.ViewModels.Kontakt
{
    public class KontaktIndexVM
    {
       public string Narucilac { get; set; }

       public string Email { get; set; }

        public string Poruka { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MimeKit;
using MailKit.Net.Smtp;
using WebApplication1.Helper;
using WebApplication1.EF;
using WebApplication1.Areas.ModulKorisnik.ViewModels.Kontakt;
using WebApplication1.Models;

namespace WebApplication1.Areas.ModulKorisnik.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: true)]

    [Area("ModulKorisnik")]
    [Route("/ModulKorisnik/Kontakt")]
    public class KontaktController : Controller
    {
        private const string LogiraniKorisnik = "logirani_korisnik";
        private MyContext _db;
        public KontaktController(MyContext db)
        {
            _db = db;
        }

        [Route("/ModulKorisnik/Kontakt/Index")]
        public IActionResult Index()
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();
            Narucilac n = _db.Narucilac.Where(q => q.KorisnickiNalogId == korisnik.Id).FirstOrDefault();

            KontaktIndexVM model = new KontaktIndexVM();
            
            model.Narucilac = n.ImePrezime;
            model.Email = n.Email;
           
            return View(model);
        }

        [Route("/ModulKorisnik/Kontakt/Posalji")]
        public IActionResult Posalji(KontaktIndexVM model)
        {
           
            var message = new MimeMessage();

            message.From.Add(new MailboxAddress("Semir", "eRestoran2020@gmail.com"));
            message.To.Add(new MailboxAddress("Semir", "eRestoran2020@gmail.com"));
            message.Subject = "Poruka od korisnika";

            message.Body = new TextPart("plain")
            {
                Text = model.Poruka + " Poruka poslana od: " + model.Narucilac
            };

            using (var client = new SmtpClient())
            {
                client.Connect("smtp.gmail.com", 587, false);
                client.Authenticate("eRestoran2020@gmail.com", "restoran123");

                client.Send(message);

                client.Disconnect(true);
            }

            return Redirect("/ModulKorisnik/Home/Index");
        }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/Views/Kontakt/Index.cshtml
@model WebApplication1.Areas.ModulKorisnik.ViewModels.Kontakt.KontaktIndexVM


<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Posaljite email</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form asp-area="ModulKorisnik" asp-controller="Kontakt" asp-action="Posalji" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Narucilac">
                            Ime i prezime:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Narucilac" autofocus class="form-control" readonly />
                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Email">
                            Email:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Email" class="form-control" readonly />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Poruka">
                            Poruka:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @*<input asp-for="Poruka" class="form-control" />*@
                            <textarea asp-for="Poruka" class="form-control"></textarea>
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-9  text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" onclick="alert('Poruka je poslana!')" class="btn btn-success">Posalji</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>