webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/ViewModels/Narucilac/NarucilacDodajVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Narucilac
{
    public class NarucilacDodajVM
    {
        
        public int NarucilacId { get; set; }

        [BindRequired]
        public int GradId { get; set; }
        public List<SelectListItem> gradLista { get; set; }

        [Required(ErrorMessage ="Ime i prezime je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Ime mora imat više od 4 slova")]
        public string ImePrezime { get; set; }

        [Required(ErrorMessage = "Korisnicko ime je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Ime mora imat više od 4 slova")]
        public string KorisnickoIme { get; set; }
        public string Email { get; set;}

        [Required(ErrorMessage = "Telefon je obavezno polje")]
        [RegularExpression("^[0-9]{6,11}$", ErrorMessage = "Telefon mora imat više od 5 cifri")]
        public string Telefon { get; set; }

        [Required(ErrorMessage = "Adresa je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Adresa mora imat više od 4 slova")]
        public string Adresa { get; set; }

        [Required(ErrorMessage = "Lozinka je obavezno polje")]
        [RegularExpression("^.{8,}$", ErrorMessage = "Lozinka mora imat više od 8 karaktera")]
        public string Lozinka { get;  set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/ViewModels/Narucilac/NarucilacListVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulAdmin.ViewModels.Narucilac
{
   
    public class NarucilacListVM
    {
        public List<Row> htmlRows { get; set; }
        public class Row
        {
            public string NarucilacId { get; set; }
            public string ImePrezime { get; set; }
            public string KorisnickoIme { get; set; }
            public string Email { get; set; }
            public string Telefon { get; set; }
            public string Adresa { get; set; }
            public string GradNaziv { get; set; }
        }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/ViewModels/Narucilac/NarucilacIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Areas.ModulKorisnik.ViewModels.Narucilac
{
    public class NarucilacIndexVM
    {
        public int NarucilacId { get; internal set; }
        public string ImePrezime { get; internal set; }
        public string KorisnickoIme { get; internal set; }
        public string Email { get; internal set; }
        public string Telefon { get; internal set; }
        public string Adresa { get; internal set; }
        public string Lozinka { get; internal set; }
        public int KorisnickiNalogId { get; internal set; }
        public string GradNaziv { get; internal set; }
        public int GradId { get; internal set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/ViewModels/Narucilac/NarucilacUrediVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Areas.ModulKorisnik.ViewModels.Narucilac
{
    public class NarucilacUrediVM
    {
        public int NarucilacId { get; set; }

        [BindRequired]
        public int GradId { get; set; }
        public List<SelectListItem> gradLista { get; set; }

        [Required(ErrorMessage = "Ime i prezime je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Ime mora imat više od 4 slova")]
        public string ImePrezime { get; set; }

        [Required(ErrorMessage = "Korisnicko ime je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Ime mora imat više od 4 slova")]
        public string KorisnickoIme { get; set; }
        public string Email { get; set; }

        [Required(ErrorMessage = "Telefon je obavezno polje")]
        [RegularExpression("^[0-9]{6,11}$", ErrorMessage = "Telefon mora imat više od 5 cifri")]
        public string Telefon { get; set; }

        [Required(ErrorMessage = "Adresa je obavezno polje")]
        [RegularExpression("^.{4,}$", ErrorMessage = "Adresa mora imat više od 4 slova")]
        public string Adresa { get; set; }

        [Required(ErrorMessage = "Lozinka je obavezno polje")]
        [RegularExpression("^.{8,}$", ErrorMessage = "Lozinka mora imat više od 8 karaktera")]
        public string Lozinka { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Models/Narucilac.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Narucilac
    {
        [Key]
        public int NarucilacId { get; set; }
        public string ImePrezime { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Adresa { get; set; }
        public int GradId { get; set; }
        [ForeignKey("GradId")]
        public Grad Grad { get; set; }

        public int? KorisnickiNalogId { get; set; }
        [ForeignKey("KorisnickiNalogId")]
        public KorisnickiNalog KorisnickiNalog { get; set; }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulAdmin/Controllers/NarucilacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Areas.ModulAdmin.ViewModels.Narucilac;
using WebApplication1.Helper;

namespace WebApplication1.Areas.ModulAdmin.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: false)]

    [Area("ModulAdmin")]
    [Route("/ModulAdmin/Narucilac")]
    public class NarucilacController : Controller
    {
        private MyContext db;
        public NarucilacController(MyContext baza)
        {
            db = baza;
        }

   
        [Route("/ModulAdmin/Narucilac/List")]
        public IActionResult List()
        {

            NarucilacListVM model = new NarucilacListVM
            {
                htmlRows = db.Narucilac.Select(n => new NarucilacListVM.Row
                {
                    NarucilacId = n.NarucilacId.ToString(),
                    ImePrezime = n.ImePrezime,
                    KorisnickoIme = n.KorisnickiNalog.KorisnickoIme,
                    Email = n.Email,
                    Telefon = n.Telefon,
                    Adresa = n.Adresa,
                    GradNaziv = n.Grad.Naziv
                }).ToList()
            };

            return View(model);
        }
        [Route("/ModulAdmin/Narucilac/Obrisi")]
        [HttpGet]
        public IActionResult Obrisi(int id)
        {
            Narucilac obrisati = db.Narucilac.SingleOrDefault(n => n.NarucilacId == id);

            if (obrisati == null)
                return View("Error");

            db.Remove(obrisati);
            db.SaveChanges();
            TempData["porukaDelete"] = "Uspjesno obrisan korisnik";

            return RedirectToAction("List");
        }


        [Route("/ModulAdmin/Narucilac/Dodaj")]
        public IActionResult Dodaj()
        {

            var model = new NarucilacDodajVM();
            GenerisiCmbStavke(model);
            

            return View(model);
        }

        private void GenerisiCmbStavke(NarucilacDodajVM model)
        {
            model.gradLista = db.Grad.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.GradId.ToString()
            }).ToList();

        }

        [Route("/ModulAdmin/Narucilac/Uredi")]
        public IActionResult Uredi(int id)
        {
            Narucilac n = db.Narucilac.Find(id);
            KorisnickiNalog kn = db.KorisnickiNalog.Where(w => w.Id == n.KorisnickiNalogId).SingleOrDefault();

            NarucilacDodajVM model = new NarucilacDodajVM();
            GenerisiCmbStavke(model);
            model.NarucilacId = id;
            model.ImePrezime = n.ImePrezime;
            model.GradId = n.GradId;
            model.KorisnickoIme = n.KorisnickiNalog.KorisnickoIme;
            model.Lozinka = n.KorisnickiNalog.Lozinka;

            model.Telefon = n.Telefon;
            model.Email = n.Email;
            model.Adresa = n.Adresa;
           
            GenerisiCmbStavke(model);
            return View(model);
        }

        [Route("/ModulAdmin/Narucilac/DodajSave")]
        [HttpPost]
        public IActionResult DodajSave(NarucilacDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Narucilac n = db.Narucilac.Find(model.NarucilacId);
                KorisnickiNalog kn = new KorisnickiNalog();

                if (n == null)
                {
                    n = new Narucilac();
 
                    db.Add(n);
                    db.Add(kn);

                }

                kn.KorisnickoIme = model.KorisnickoIme;
                kn.Lozinka = model.Lozinka;


                n.ImePrezime = model.ImePrezime;
                n.KorisnickiNalogId = kn.Id;
                n.Email = model.Email;
                n.Telefon = model.Telefon;
                n.Adresa = model.Adresa;
                n.GradId = model.GradId;

                db.SaveChanges();
                return RedirectToAction("List");

            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Dodaj",model);

            }
        }
       

        [Route("/ModulAdmin/Narucilac/UrediSave")]
        [HttpPost]
        public IActionResult UrediSave(NarucilacDodajVM model)
        {
            if (ModelState.IsValid)
            {
                Narucilac n = db.Narucilac.Find(model.NarucilacId);
                KorisnickiNalog kn = db.KorisnickiNalog.Where(w => w.Id == n.KorisnickiNalogId).FirstOrDefault();

                if (n == null)
                {
                    n = new Narucilac();
                    kn = new KorisnickiNalog();
                    db.Add(kn);
                    db.Add(n);

                }
                kn.KorisnickoIme = model.KorisnickoIme;
                kn.Lozinka = model.Lozinka;
                n.ImePrezime = model.ImePrezime;
                n.KorisnickiNalogId = kn.Id;
                n.Email = model.Email;
                n.Telefon = model.Telefon;
                n.Adresa = model.Adresa;
                n.GradId = model.GradId;

                db.SaveChanges();
                return RedirectToAction("List");

            }
            else
            {
                GenerisiCmbStavke(model);
                return View("Uredi", model);

            }
        }
    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/Controllers/NarucilacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Helper;
using WebApplication1.Areas.ModulKorisnik.ViewModels.Narucilac;

namespace WebApplication1.Areas.ModulKorisnik.Controllers
{
    [Autorizacija(zaposlenik: true, korisnik: true)]

    [Area("ModulKorisnik")]
    [Route("/ModulKorisnik/Narucilac")]
    public class NarucilacController : Controller
    {
        private MyContext _db;
        public NarucilacController(MyContext db)
        {
            _db = db;
        }

        [Route("/ModulKorisnik/Narucilac/Index")]
        public IActionResult Index(int KorisnikId)
        {
            Narucilac n = _db.Narucilac.Where(s => s.KorisnickiNalogId == KorisnikId).FirstOrDefault();

            KorisnickiNalog kn = _db.KorisnickiNalog.Where(w => w.Id == KorisnikId).SingleOrDefault();

            NarucilacIndexVM model = new NarucilacIndexVM();
            
            model.NarucilacId = n.NarucilacId;
            model.ImePrezime = n.ImePrezime;
            model.GradId = n.GradId;
            model.GradNaziv = _db.Grad.Where(q=> q.GradId == n.GradId).Select(q=> q.Naziv).FirstOrDefault();
            model.KorisnickoIme = n.KorisnickiNalog.KorisnickoIme;
            model.Lozinka = n.KorisnickiNalog.Lozinka;

            model.Telefon = n.Telefon;
            model.Email = n.Email;
            model.Adresa = n.Adresa;

            
            return View(model);
        }

        [Route("/ModulKorisnik/Narucilac/Uredi")]
        public IActionResult Uredi(int NarucilacId, int KorisnickiNalogId)
        {
            Narucilac n = _db.Narucilac.Find(NarucilacId);
            KorisnickiNalog kn = _db.KorisnickiNalog.Where(w => w.Id == n.KorisnickiNalogId).SingleOrDefault();

            NarucilacUrediVM model = new NarucilacUrediVM();

            model.gradLista = _db.Grad.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.GradId.ToString()
            }).ToList();

            model.NarucilacId = NarucilacId;
            model.ImePrezime = n.ImePrezime;
            model.GradId = n.GradId;
            model.KorisnickoIme = n.KorisnickiNalog.KorisnickoIme;
            model.Lozinka = n.KorisnickiNalog.Lozinka;

            model.Telefon = n.Telefon;
            model.Email = n.Email;
            model.Adresa = n.Adresa;

            model.gradLista = _db.Grad.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.GradId.ToString()
            }).ToList();

            return View(model);
        }

        [Route("/ModulKorisnik/Narucilac/UrediSave")]
        [HttpPost]
        public IActionResult UrediSave(NarucilacUrediVM model)
        {
            
                Narucilac n = _db.Narucilac.Find(model.NarucilacId);
                KorisnickiNalog kn = _db.KorisnickiNalog.Where(w => w.Id == n.KorisnickiNalogId).FirstOrDefault();

                if (n == null)
                {
                    n = new Narucilac();
                    kn = new KorisnickiNalog();
                    _db.Add(kn);
                    _db.Add(n);

                }
                kn.KorisnickoIme = model.KorisnickoIme;
                kn.Lozinka = model.Lozinka;
                n.ImePrezime = model.ImePrezime;
                n.KorisnickiNalogId = kn.Id;
                n.Email = model.Email;
                n.Telefon = model.Telefon;
                n.Adresa = model.Adresa;
                n.GradId = model.GradId;

                _db.SaveChanges();
                return Redirect("/ModulKorisnik/Narucilac/Index?KorisnikId=" + kn.Id);            
        }
    }
    
}

webapp/online_restoran_app/WebApplication1/Controllers/NarucilacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.EF;
using WebApplication1.Models;
using WebApplication1.Models.ViewModels;

namespace WebApplication1.Controllers
{
    public class NarucilacController : Controller
    {
        private MyContext _db;
        public NarucilacController(MyContext db)
        {
            _db = db;
        }

        public IActionResult Dodaj()
        {
            var model = new NarucilacDodajVM();

            model.gradLista = _db.Grad.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.GradId.ToString()
            }).ToList();

            return View(model);
        }

        public IActionResult DodajSave(NarucilacDodajVM model)
        {
           
                Narucilac n = _db.Narucilac.Find(model.NarucilacId);
                KorisnickiNalog kn = new KorisnickiNalog();

                if (n == null)
                {
                    n = new Narucilac();

                    _db.Add(n);
                    _db.Add(kn);

                }

                kn.KorisnickoIme = model.KorisnickoIme;
                kn.Lozinka = model.Lozinka;


                n.ImePrezime = model.ImePrezime;
                n.KorisnickiNalogId = kn.Id;
                n.Email = model.Email;
                n.Telefon = model.Telefon;
                n.Adresa = model.Adresa;
                n.GradId = model.GradId;

                _db.SaveChanges();
             
           
            return Redirect("~/Autentifikacija");
        }


    }
}

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/Views/Narucilac/Index.cshtml
@model WebApplication1.Areas.ModulKorisnik.ViewModels.Narucilac.NarucilacIndexVM




<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Vas profil</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form asp-area="ModulAdmin" asp-controller="Narucilac" asp-action="UrediSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="ImePrezime">
                            Ime i prezime:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="ImePrezime" autofocus class="form-control" readonly/>
                            <span asp-validation-for="ImePrezime"></span>
                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="KorisnickoIme">
                            Korisničko ime:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="KorisnickoIme" class="form-control" readonly/>
                            <span asp-validation-for="KorisnickoIme"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Lozinka">
                            Lozinka:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Lozinka" class="form-control" readonly/>
                            <span asp-validation-for="Lozinka"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Email">
                            Email:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Email" type="email" class="form-control" readonly/>

                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Telefon">
                            Telefon:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Telefon" class="form-control" readonly/>
                            <span asp-validation-for="Telefon"></span>


                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Adresa">
                            Adresa:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Adresa" class="form-control" readonly/>
                            <span asp-validation-for="Adresa"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="GradNaziv">
                            Grad:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="GradNaziv" class="form-control" readonly/>
                            <span asp-validation-for="GradNaziv"></span>

                        </div>
                    </div>

                    <input asp-for="NarucilacId" type="hidden" />
                    <input asp-for="KorisnickiNalogId" type="hidden" />

                    <div class="form-group">
                        <div class="col-md-9  text-right">                            
                            <a asp-area="ModulKorisnik" asp-controller="Narucilac" asp-route-NarucilacId="@Model.NarucilacId" asp-route-KorisnickiNalogId="@Model.KorisnickiNalogId" asp-action="Uredi" class="btn btn-success">Uredi</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

webapp/online_restoran_app/WebApplication1/Areas/ModulKorisnik/Views/Narucilac/Uredi.cshtml
@model WebApplication1.Areas.ModulKorisnik.ViewModels.Narucilac.NarucilacUrediVM



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Uredite vas profil</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form asp-area="ModulKorisnik" asp-controller="Narucilac" asp-action="UrediSave" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="ImePrezime">
                            Ime i prezime:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="ImePrezime" autofocus class="form-control" />
                            <span asp-validation-for="ImePrezime"></span>
                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="KorisnickoIme">
                            Korisničko ime:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="KorisnickoIme" class="form-control" />
                            <span asp-validation-for="KorisnickoIme"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Lozinka">
                            Lozinka:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Lozinka" class="form-control" />
                            <span asp-validation-for="Lozinka"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Email">
                            Email:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Email" type="email" class="form-control" />

                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Telefon">
                            Telefon:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Telefon" class="form-control" />
                            <span asp-validation-for="Telefon"></span>


                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Adresa">
                            Adresa:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="Adresa" class="form-control" />
                            <span asp-validation-for="Adresa"></span>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Grad">
                            Grad:
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select asp-for="GradId" asp-items="Model.gradLista" class="form-control">
                                <option value="" disabled hidden selected>(Odaberi grad)</option>
                            </select>
                            <span asp-validation-for="GradId"></span>
                        </div>
                    </div>

                    <input asp-for="NarucilacId" type="hidden" />

                    <div class="form-group">
                        <div class="col-md-9  text-right">
                            <button type="reset" class="btn btn-primary">Resetiraj</button>
                            <button type="submit" class="btn btn-success">Uredi</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>